# SPDX-FileCopyrightText: 2026 Maximilian Kenfenheuer
# SPDX-License-Identifier: Apache-2.0

unit_test_sources += files(
  'test_autodetect.cpp',
  'test_capabilities.cpp',
  'test_framing.cpp',
  'test_gcc.cpp',
  'test_input.cpp',
  'test_mcs.cpp',
  'test_output.cpp',
  'test_pointer.cpp',
  'test_spec_activation.cpp',
  'test_spec_vectors.cpp',
  'test_x224.cpp',
)
unit_test_deps += farland_proto_dep
