version = 1

# Files that cannot or do not carry SPDX headers themselves.
[[annotations]]
path = [
  "**/*.md",
  "fuzz/corpus/**",
  "tests/data/**",
  "subprojects/*.wrap",
  ".clang-format",
  ".clang-tidy",
  ".editorconfig",
  ".gitignore",
  ".pre-commit-config.yaml",
  "NOTICE",
  "REUSE.toml",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Maximilian Kenfenheuer"
SPDX-License-Identifier = "Apache-2.0"
