# SPDX-FileCopyrightText: 2026 Maximilian Kenfenheuer
# SPDX-License-Identifier: Apache-2.0

unit_test_sources += files(
  'test_audio_playback.cpp',
  'test_autodetect.cpp',
  'test_broker.cpp',
  'test_camera.cpp',
  'test_clipboard_bridge.cpp',
  'test_clipboard_files.cpp',
  'test_compositor.cpp',
  'test_connection.cpp',
  'test_cursor_encoder.cpp',
  'test_display_control.cpp',
  'test_display_layout.cpp',
  'test_dynamic_channels.cpp',
  'test_frame_encoder.cpp',
  'test_frame_scheduler.cpp',
  'test_graphics_pipeline.cpp',
  'test_latency.cpp',
  'test_preauth.cpp',
  'test_privsep.cpp',
  'test_quality_controller.cpp',
  'test_scroll_detector.cpp',
  'test_touch_input.cpp',
)
unit_test_deps += [farland_server_dep, farland_platform_dep]
