# SPDX-FileCopyrightText: 2026 Maximilian Kenfenheuer
# SPDX-License-Identifier: Apache-2.0

unit_test_sources += files(
  'test_auto_reconnect.cpp',
  'test_credential_store.cpp',
  'test_credssp.cpp',
  'test_kerberos.cpp',
  'test_ntlm.cpp',
  'test_spnego.cpp',
  'test_tls.cpp',
  'test_tls_identity.cpp',
)
unit_test_deps += farland_auth_dep
