# SPDX-FileCopyrightText: 2026 Maximilian Kenfenheuer
# SPDX-License-Identifier: Apache-2.0

unit_test_sources += files(
  'test_audin.cpp',
  'test_clipboard_formats.cpp',
  'test_cliprdr.cpp',
  'test_cliprdr_server.cpp',
  'test_disp.cpp',
  'test_drdynvc.cpp',
  'test_dvc_server.cpp',
  'test_rdpecam.cpp',
  'test_rdpei.cpp',
  'test_rdpei_server.cpp',
  'test_rdpgfx.cpp',
  'test_rdpgfx_server.cpp',
  'test_rdpsnd.cpp',
  'test_svc.cpp',
)
unit_test_deps += farland_channels_dep
